name: gossip_workspace
repository: https://github.com/neutrinographics/gossip

packages:
  - packages/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- dart analyze .
    description: Run dart analyze in all packages

  test:
    run: melos exec -- dart test
    packageFilters:
      dirExists: test
    description: Run tests in all packages

  format:
    run: melos exec -- dart format .
    description: Format all packages

  format:check:
    run: melos exec -- dart format --set-exit-if-changed .
    description: Check formatting in all packages
